repos:
  - repo: https://github.com/ambv/black
    rev: 22.6.0
    hooks:
      - id: black
        language_version: python3.9
  - repo: https://github.com/pycqa/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
  - repo: https://github.com/PyCQA/docformatter
    rev: v1.5.0
    hooks:
      - id: docformatter
        name: docformatter
        description: "Formats docstrings to follow PEP 257."
        entry: docformatter
        args: [--in-place]
        language: python
        types: [python]

  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.1.1 # pick a git hash / tag to point to
    hooks:
      - id: pydocstyle
        args:
          - --ignore=D101,D105,D203,D213,D401,D406,D407,D413
          - --ignore-decorators

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: "mypy"
        language: python
        exclude: ^tests/
        types: [python]
        verbose: true
        args: 
          - --no-strict-optional
          - --ignore-missing-imports
          - --no-incremental
          - --disable-error-code=override
        additional_dependencies: [types-all]

  - repo: local
    hooks:
      - id: pytest
        name: run tests
        entry: pytest tests -vv
        language: system
        always_run: true
        pass_filenames: false
