name: Update Coverage on Readme
on:
  push:
    branches:
      - feature/#123_Look-into-ways-to-shorten-the-import-paths
jobs:
  update-coverage-on-readme:
    runs-on: ubuntu-latest
    needs: pytest_coverage
    steps:
      - uses: actions/checkout@v3
        with:
          ref:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
        
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          path: artifacts

      - name: Extract branch name
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Pytest coverage comment
        #if: ${{ github.ref == 'refs/heads/feature/#123_Look-into-ways-to-shorten-the-import-paths' }}
        id: coverageComment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          hide-comment: true
          pytest-coverage-path: artifacts/coverage-results/pytest-coverage.txt
          junitxml-path: artifacts/pytest-xml/pytest.xml

      - name: Create Variable of Summary Report
        id: summary_report
        run: |
          SUMMARY_REPORT=${{ steps.coverageComment.outputs.summaryReport }}
          echo "::set-output name=content::$SUMMARY_REPORT"

      - name: Update Readme with Coverage Html
        #if: ${{ github.ref == 'refs/heads/feature/#123_Look-into-ways-to-shorten-the-import-paths' }}
        run: |
          sed -i '/<!-- Pytest Coverage Comment:Begin -->/,/<!-- Pytest Coverage Comment:End -->/c\<!-- Pytest Coverage Comment:Begin -->\n\${{ steps.summary_report.outputs.content }}\n<!-- Pytest Coverage Comment:End -->' ./README.md

      - name: Commit & Push changes to Readme
        #if: ${{ github.ref == 'refs/heads/feature/#123_Look-into-ways-to-shorten-the-import-paths' }}
        uses: actions-js/push@master
        with:
          message: Update coverage on Readme
          github_token: ${{ secrets.GITHUB_TOKEN }}