# This workflow will install dependencies, create coverage tests and run Pytest Coverage Comment
# For more information see: https://github.com/MishaKav/pytest-coverage-comment/
name: pytest-coverage-comment
on:
  pull_request:
    branches:
      - '*'
jobs:
  pytest_coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.7.12

      - name: Installing requirements
        run: |
          pip3 install -r requirements/requirements.txt

      - name: Run pytest and coverage
        run: |
          pytest --junitxml=pytest.xml --cov-report=term-missing:skip-covered --cov=dialoguekit tests/ | tee pytest-coverage.txt


      - name: Upload Coverage Results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: coverage-results
          path: ./pytest-coverage.txt

      - name: Upload Unit Test Results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: pytest-xml
          path: ./pytest.xml

  pytest_coverage_comment:
    runs-on: ubuntu-latest
    needs: pytest_coverage
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          path: artifacts

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          files: artifacts/unit-test-py37/*.xml

      - name: Pytest coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: ./artifacts/coverage-results/pytest-coverage.txt
          title: My Coverage Report Title
          badge-title: Coverage
          hide-badge: false
          hide-report: false
          create-new-comment: false
          hide-comment: false
          report-only-changed-files: false
          remove-link-from-badge: false
          junitxml-path: ./path-to-file/pytest.xml
          junitxml-title: My JUnit Xml Summary Title
