name: Sphinx docs to gh-pages

on:
  push:
    branches:
      - documentation/#98-read-the-docs

# workflow_dispatch:        # Un comment line if you also want to trigger action manually

jobs:
  sphinx_docs_to_gh-pages:
    runs-on: ubuntu-latest
    name: Sphinx docs to gh-pages
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7.12
      - name: pwd
        run: |
          pwd
      - name: ls
        run: |
          ls
      - name: cd ..
        run: |
          cd ..
      - name: pwd
        run: |
          pwd
      - name: ls
        run: |
          ls
      - name: Installing the Documentation requirements
        run: |
          pip3 install .[docs]
      - name: Installing the library
        shell: bash -l {0}
        run: |
          python setup.py install
      - name: Running the Sphinx to gh-pages Action
        uses: uibcdf/action-sphinx-docs-to-gh-pages@v1.0.0
        with:
          branch: documentation/#98-read-the-docs
          dir_docs: docs
          sphinxapiopts: '--separate -o . ../'
          sphinxapiexclude: '../*setup* ../*.ipynb'
          sphinxopts: ''